# Generated by Django 6.1 on 2026-08-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='salary_estimate',
        ),
    ]
