# Generated by Django 6.1 on 2026-08-26 09:57

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_salary_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/phsr/workspace/active/job_application_tracker/cover_letters'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/phsr/workspace/active/job_application_tracker/resumes'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.platform'),
        ),
    ]
